apiVersion: apps/v1
kind: Deployment
metadata:
  name: vsftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      name: vsftpd
      app: vsftpd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: vsftpd
        app: vsftpd
    spec:
      containers:
      - image: my-image
        name: vsftpd
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21100
        - containerPort: 21101
        - containerPort: 21102
        - containerPort: 21103
        - containerPort: 21104
        - containerPort: 21105
        - containerPort: 21106
        - containerPort: 21107
        - containerPort: 21108
        - containerPort: 21109
        - containerPort: 21110
        resources: {}
        imagePullPolicy: Never 
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: vsftpd
spec:
  ports:
  - name: "20"
    port: 20
    targetPort: 20
  - name: "21"
    port: 21
    targetPort: 21
  - name: "21100"
    port: 21100
    targetPort: 21100
  - name: "21101"
    port: 21101
    targetPort: 21101
  - name: "21102"
    port: 21102
    targetPort: 21102
  - name: "21103"
    port: 21103
    targetPort: 21103
  - name: "21104"
    port: 21104
    targetPort: 21104
  - name: "21105"
    port: 21105
    targetPort: 21105
  - name: "21106"
    port: 21106
    targetPort: 21106
  - name: "21107"
    port: 21107
    targetPort: 21107
  - name: "21108"
    port: 21108
    targetPort: 21108
  - name: "21109"
    port: 21109
    targetPort: 21109
  - name: "21110"
    port: 21110
    targetPort: 21110
  selector:
    app: vsftpd

